const escapeHtml=value=>String(value??'').replace(/[<>&"']/g,character=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[character]));
const slugify=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
let catalog=null,current=0;
document.querySelector('.dimensions-page h1').innerHTML='6 DIMENSÕES DE <em>MATURIDADE</em>';
document.querySelector('.dimensions-page>header p').textContent='Qualidade de Código, Design de Software, Resiliência, Segurança, Observabilidade e Operabilidade avaliadas por evidências objetivas.';
document.getElementById('dimension-tabs').classList.add('six-dimensions');

const structureButton=document.createElement('button');
structureButton.id='show-dimension-structure';structureButton.className='structure-button';structureButton.innerHTML='<span aria-hidden="true">⌘</span> Ver estrutura';
document.querySelector('.dimensions-page>header').appendChild(structureButton);
const structureDialog=document.createElement('dialog');
structureDialog.id='dimension-structure-dialog';structureDialog.className='structure-dialog';structureDialog.innerHTML='<div class="structure-shell"><header><div><span class="eyebrow">Mapa do contrato</span><h2>ESTRUTURA DAS <em>DIMENSÕES</em></h2><p>Dimensões, pesos e subdimensões avaliadas pelo sistema de maturidade.</p></div><button class="structure-close" aria-label="Fechar" title="Fechar">×</button></header><div class="structure-tree" id="dimension-structure-tree"></div><footer><button class="structure-done">Fechar</button></footer></div>';
document.body.appendChild(structureDialog);

function renderDimensionStructure(){document.getElementById('dimension-structure-tree').innerHTML=`<div class="tree-root"><b>MATURIDADE DO MICROSSERVIÇO</b><span>${catalog.summary.dimensions} dimensões · ${catalog.summary.subdimensions} subdimensões</span></div>`+catalog.dimensions.map((dimension,index)=>{const subdimensions=dimension.subdimensions||[...new Set(dimension.criteria.map(item=>item.subdimension))],weight=Math.round((catalog.weights?.[dimension.id]||0)*100);return `<section class="tree-dimension"><header><span>${escapeHtml(dimension.display_code||String(index+1).padStart(2,'0'))}</span><b>${escapeHtml(dimension.name)}</b><strong>${weight}%</strong></header><ul>${subdimensions.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul></section>`;}).join('');}
structureButton.onclick=()=>{if(catalog){renderDimensionStructure();structureDialog.showModal();}};
structureDialog.querySelector('.structure-close').onclick=structureDialog.querySelector('.structure-done').onclick=()=>structureDialog.close();
structureDialog.onclick=event=>{if(event.target===structureDialog)structureDialog.close();};

function splitMetadata(value,type){const text=String(value??'').trim();if(!text)return['Não informado'];const separator=type==='tool'?/\s*(?:\/|\+|,)\s*/:/\s*(?:,|;|\se\s)\s*/i;return text.split(separator).map(item=>item.trim()).filter(Boolean);}
function metadataChips(value,type){return splitMetadata(value,type).map(item=>`<span class="metadata-chip ${type}">${escapeHtml(item)}</span>`).join('');}
function groupCriteria(criteria){return[...criteria.reduce((groups,item)=>{if(!groups.has(item.subdimension))groups.set(item.subdimension,[]);groups.get(item.subdimension).push(item);return groups;},new Map()).entries()];}

function criterionCard(item,index){const detailId=`criterion-${current}-${slugify(item.id||index)}`;return `<details class="criterion-card" id="${detailId}"><summary aria-controls="${detailId}-details"><span class="criterion-copy"><strong>${escapeHtml(item.criterion)}</strong><span>${escapeHtml(item.evaluates)}</span></span><code>${escapeHtml(item.id)}</code><span class="accordion-control" aria-hidden="true"></span></summary><div class="criterion-details" id="${detailId}-details"><section><span class="detail-label">Como será verificado</span><div class="metadata-list">${metadataChips(item.tool||'Expert-Code-Flow','tool')}</div></section><section><span class="detail-label">Onde será analisado</span><div class="metadata-list">${metadataChips(item.sources,'source')}</div></section><section class="expected-evidence"><span class="detail-label">Evidência esperada</span><p>${escapeHtml(item.expected_evidence||'Não informada')}</p></section></div></details>`;}
function subdimensionSection(subdimension,items,index){const sectionId=`subdimension-${current}-${slugify(subdimension)}`;return `<section class="subdimension-section" id="${sectionId}"><header><div><span class="section-index">${String(index+1).padStart(2,'0')}</span><h3>${escapeHtml(subdimension)}</h3><p>Avalia ${escapeHtml(subdimension.toLowerCase())} por meio de critérios e evidências objetivas.</p></div><span class="criterion-count">${items.length} ${items.length===1?'critério':'critérios'}</span></header><div class="criterion-list">${items.map(criterionCard).join('')}</div></section>`;}

function renderCriteria(){
 const dimension=catalog.dimensions[current],weight=Math.round((catalog.weights?.[dimension.id]||0)*100),query=document.getElementById('criteria-search').value.trim().toLowerCase(),allGroups=groupCriteria(dimension.criteria),criteria=dimension.criteria.filter(item=>!query||JSON.stringify(item).toLowerCase().includes(query)),groups=groupCriteria(criteria);
 document.getElementById('dimension-position').textContent=`Dimensão ${current+1} de ${catalog.dimensions.length}`;document.getElementById('dimension-title').textContent=dimension.name;document.getElementById('dimension-description').textContent=dimension.description;document.getElementById('dimension-subdimension-count').textContent=`${allGroups.length} subdimensões`;document.getElementById('dimension-criterion-count').textContent=`${dimension.criteria.length} critérios`;document.getElementById('dimension-weight').textContent=`Peso ${weight}%`;
 document.getElementById('subdimension-navigation').innerHTML=allGroups.map(([name])=>`<a href="#subdimension-${current}-${slugify(name)}">${escapeHtml(name)}</a>`).join('');
 document.getElementById('criteria-body').innerHTML=groups.length?groups.map(([name,items],index)=>subdimensionSection(name,items,index)).join(''):'<div class="empty-state"><strong>Nenhum critério encontrado</strong><span>Tente buscar por outro nome, código, ferramenta ou arquivo.</span></div>';
 document.getElementById('visible-count').textContent=query?`${criteria.length} critério(s) encontrado(s) em ${groups.length} subdimensão(ões)`:`${dimension.criteria.length} critérios · ${allGroups.length} subdimensões`;
 document.querySelectorAll('.subdimension-navigation a').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();const target=document.getElementById(link.getAttribute('href').slice(1));if(target)target.scrollIntoView({behavior:'smooth',block:'start'});}));
}
function selectDimension(index,focus=false){current=index;document.querySelectorAll('.dimension-tab').forEach((button,buttonIndex)=>{const active=buttonIndex===index;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;if(active){button.scrollIntoView({behavior:'smooth',block:'nearest',inline:'nearest'});if(focus)button.focus();}});renderCriteria();}
function handleDimensionKeys(event){const tabs=[...document.querySelectorAll('.dimension-tab')],index=tabs.indexOf(event.currentTarget);let next=index;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();selectDimension(next,true);}

fetch('/api/maturity/dimensions').then(response=>{if(!response.ok)throw new Error('Falha ao carregar o catálogo');return response.json();}).then(data=>{catalog=data;document.getElementById('dimension-count').textContent=data.summary.dimensions;document.getElementById('subdimension-count').textContent=data.summary.subdimensions;document.getElementById('criteria-count').textContent=data.summary.criteria;document.getElementById('catalog-version').textContent=data.summary.version;const tablist=document.getElementById('dimension-tabs');tablist.setAttribute('role','tablist');tablist.innerHTML=data.dimensions.map((item,index)=>`<button class="dimension-tab ${index===0?'active':''}" data-index="${index}" role="tab" tabindex="${index===0?'0':'-1'}" aria-selected="${index===0}"><span>${escapeHtml(item.display_code||String(index+1).padStart(2,'0'))}</span><b>${escapeHtml(item.name)}</b><strong>${Math.round((data.weights?.[item.id]||0)*100)}%</strong></button>`).join('');document.querySelectorAll('.dimension-tab').forEach(button=>{button.addEventListener('click',()=>selectDimension(Number(button.dataset.index)));button.addEventListener('keydown',handleDimensionKeys);});renderCriteria();}).catch(error=>{document.getElementById('criteria-body').innerHTML=`<div class="error">${escapeHtml(error.message)}</div>`;});
document.getElementById('criteria-search').addEventListener('input',()=>catalog&&renderCriteria());
