const storeKey='expert-code-flow:maturity-results',modelVersion='SIX_DIMENSIONS_OBJECTIVE_MODEL_1.0';
const resultLabels={ADHERENT:'Aderente',PARTIALLY_ADHERENT:'Parcialmente aderente',NON_ADHERENT:'Não aderente',NOT_APPLICABLE:'Não aplicável'};
const confidenceLabels={HIGH:'Alta',MEDIUM:'Média',LOW:'Baixa',NOT_AVAILABLE:'Não disponível'};
let report,catalog,activeId=new URLSearchParams(location.search).get('dimension'),statusFilter='ALL',resultFilter='ALL',queryFilter='';
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function slugify(value=''){return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function load(){try{return JSON.parse(localStorage.getItem(storeKey));}catch{return null;}}
function confidence(value){return confidenceLabels[value]||value||'—';}
function percentage(value){return value===null||value===undefined?'N/A':`${value}%`;}
function groupCriteria(criteria){return[...criteria.reduce((groups,item)=>{if(!groups.has(item.subdimension))groups.set(item.subdimension,[]);groups.get(item.subdimension).push(item);return groups;},new Map()).entries()];}

function renderSummary(){
 document.getElementById('audit-service').textContent=report.context?.project_name||'Microsserviço analisado';document.getElementById('audit-date').textContent=report.generated_at?`Processado em ${new Date(report.generated_at).toLocaleString('pt-BR')}`:'Data não disponível';document.getElementById('audit-score').textContent=report.score===null?'N/A':`${report.score} / 100`;document.getElementById('audit-coverage').textContent=percentage(report.coverage_percent);document.getElementById('audit-confidence').textContent=confidence(report.confidence);document.getElementById('audit-rules').textContent=`${report.evaluated_criteria} / ${report.applicable_criteria}`;
 const scored=report.dimensions.filter(d=>d.score!==null),weightSum=scored.reduce((sum,d)=>sum+(Number(d.weight)||0),0);document.getElementById('score-calculation').innerHTML=`<div class="calculation-row header"><span>Dimensão</span><span>Score</span><span>Peso efetivo</span><span>Contribuição</span></div>`+report.dimensions.map(d=>{const effective=d.score===null||!weightSum?0:(Number(d.weight)||0)/weightSum,contribution=d.score===null?0:d.score*effective;return `<div class="calculation-row"><span>${escapeHtml(d.dimension)}</span><b>${d.score===null?'N/A':d.score}</b><span>${d.score===null?'Excluída':Math.round(effective*100)+'%'}</span><b>${d.score===null?'—':contribution.toFixed(1)}</b></div>`;}).join('')+`<div class="calculation-row"><strong>Score geral</strong><span></span><span></span><b>${report.score===null?'N/A':report.score}</b></div>`;
}

function validateContract(){
 const indicator=document.getElementById('contract-health');
 if(!catalog){indicator.className='contract-health warning';indicator.textContent='Catálogo indisponível';return;}
 const catalogIds=catalog.dimensions.flatMap(d=>d.criteria.map(c=>c.id)),reportIds=report.dimensions.flatMap(d=>d.criteria.map(c=>c.id||c.criterionId)),catalogSet=new Set(catalogIds),reportSet=new Set(reportIds),missing=catalogIds.filter(id=>!reportSet.has(id)),extra=reportIds.filter(id=>!catalogSet.has(id)),duplicates=reportIds.length-reportSet.size;
 const synchronized=!missing.length&&!extra.length&&!duplicates&&catalogIds.length===reportIds.length;
 indicator.className=`contract-health ${synchronized?'synchronized':'warning'}`;
 indicator.textContent=synchronized?`Contrato sincronizado · ${reportIds.length}/${catalogIds.length} critérios`:`Contrato divergente · ${missing.length} ausente(s), ${extra.length} extra(s), ${duplicates} duplicado(s)`;
 indicator.title=synchronized?'Todos os critérios do catálogo estão presentes no processamento.':`Ausentes: ${missing.join(', ')||'nenhum'} | Extras: ${extra.join(', ')||'nenhum'}`;
}

function selectDimension(id,focus=false){activeId=id;history.replaceState(null,'',`?dimension=${activeId}`);renderTabs();renderDimension();const selected=document.querySelector(`.dimension-card[data-id="${CSS.escape(id)}"]`);if(selected){selected.scrollIntoView({behavior:'smooth',block:'nearest',inline:'nearest'});if(focus)selected.focus();}}
function handleTabKeys(event){const tabs=[...document.querySelectorAll('.dimension-card')],index=tabs.indexOf(event.currentTarget);let next=index;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();selectDimension(tabs[next].dataset.id,true);}
function renderTabs(){const tablist=document.getElementById('audit-tabs');tablist.setAttribute('role','tablist');tablist.innerHTML=report.dimensions.map((d,index)=>{const active=d.dimension_id===activeId;return `<button class="dimension-card ${active?'active':''}" data-id="${d.dimension_id}" role="tab" tabindex="${active?'0':'-1'}" aria-selected="${active}"><span><i>${String(index+1).padStart(2,'0')}</i>${escapeHtml(d.dimension)}</span><strong>${d.score===null?'N/A':d.score}</strong><small>Cobertura ${percentage(d.coverage_percent)} · ${d.summary.evaluated_applicable} de ${d.summary.applicable} avaliadas</small></button>`;}).join('');document.querySelectorAll('.dimension-card').forEach(button=>{button.onclick=()=>selectDimension(button.dataset.id);button.onkeydown=handleTabKeys;});}

function evidenceHtml(items,inspected=[],missing=[]){const found=items?.length?items.map(e=>`<div class="evidence"><b>${escapeHtml(e.file)}</b><span>linha ${e.line||'—'}</span><code>${escapeHtml(e.snippet||'')}</code><small>Padrão: ${escapeHtml(e.pattern||'estrutural')}</small></div>`).join(''):'<p class="no-evidence">Nenhuma evidência conclusiva foi associada à decisão.</p>';const searched=inspected.length?`<p class="no-evidence"><b>Arquivos inspecionados:</b> ${inspected.map(escapeHtml).join(' · ')}</p>`:'';const absent=missing.length?`<p class="no-evidence"><b>Evidências ausentes:</b> ${missing.map(escapeHtml).join(' · ')}</p>`:'';return found+searched+absent;}
function matches(c){const queryMatch=!queryFilter||JSON.stringify(c).toLowerCase().includes(queryFilter);return queryMatch&&(statusFilter==='ALL'||statusFilter===c.processing_status)&&(resultFilter==='ALL'||resultFilter===c.result);}

function criterionCard(c){const notEvaluated=c.processing_status==='NOT_EVALUATED',processingLabel=notEvaluated?'Não avaliado':'Avaliado',processingBadge=notEvaluated?'not_evaluated':'evaluated',resultLabel=c.result?resultLabels[c.result]:'Sem resultado',resultBadge=c.result?c.result.toLowerCase():'no_result';return `<details class="audit-item"><summary><span class="audit-rule-copy"><strong>${escapeHtml(c.criterion)}</strong><span>${escapeHtml(c.reason)}</span></span><code>${escapeHtml(c.id)}</code><span class="status-pair"><span class="status ${processingBadge}">${processingLabel}</span><span class="status ${resultBadge}">${resultLabel}</span></span><span class="audit-accordion" aria-hidden="true"></span></summary><div class="audit-details"><div class="technical-grid"><span><b>O que foi verificado</b>${escapeHtml(c.evaluates)}</span><span><b>Como foi verificado</b>${escapeHtml(c.tool||'Expert-Code-Flow')}</span><span><b>Confiança</b>${Math.round((c.confidence||0)*100)}%</span><span><b>Aplicabilidade</b>${escapeHtml(c.applies_when)}</span><span><b>Pontuação</b>${c.result==='NOT_APPLICABLE'?'Excluída do score':(c.score??0)}</span></div><div class="rule-meta"><span><b>Onde foi analisado</b>${escapeHtml(c.sources)}</span><span><b>Evidência esperada</b>${escapeHtml(c.expected_evidence)}</span></div><section class="evidence-section"><h4>Evidências encontradas</h4>${evidenceHtml(c.evidence,c.inspected_files,c.missing_evidence)}</section></div></details>`;}
function subdimensionSection(name,criteria,index,dId){const id=`audit-subdimension-${slugify(dId)}-${slugify(name)}`;const attention=criteria.filter(c=>c.processing_status==='NOT_EVALUATED'||c.result==='NON_ADHERENT').length;return `<section class="audit-subdimension" id="${id}"><header><div><span>${String(index+1).padStart(2,'0')}</span><h3>${escapeHtml(name)}</h3></div><div><b>${criteria.length} ${criteria.length===1?'critério':'critérios'}</b>${attention?`<em>${attention} requer${attention===1?'':'em'} atenção</em>`:''}</div></header><div class="audit-criteria-list">${criteria.map(criterionCard).join('')}</div></section>`;}

function renderDimension(){
 const d=report.dimensions.find(item=>item.dimension_id===activeId)||report.dimensions[0];activeId=d.dimension_id;document.getElementById('audit-title').textContent=d.dimension;document.getElementById('dimension-metrics').innerHTML=`<span>Score<b>${d.score===null?'N/A':d.score+' / 100'}</b></span><span>Cobertura<b>${percentage(d.coverage_percent)}</b></span><span>Confiança<b>${confidence(d.confidence)}</b></span><span>Regras avaliadas<b>${d.summary.evaluated_applicable} de ${d.summary.applicable}</b></span>`;
 const criteria=d.criteria.filter(matches),groups=groupCriteria(criteria),allGroups=groupCriteria(d.criteria);document.getElementById('visible-count').textContent=queryFilter||statusFilter!=='ALL'||resultFilter!=='ALL'?`${criteria.length} de ${d.criteria.length} critérios em ${groups.length} subdimensão(ões)`:`${d.criteria.length} critérios · ${allGroups.length} subdimensões`;
 document.getElementById('audit-subdimension-nav').innerHTML=allGroups.map(([name])=>`<a href="#audit-subdimension-${slugify(d.dimension_id)}-${slugify(name)}">${escapeHtml(name)}</a>`).join('');document.getElementById('audit-log').innerHTML=groups.length?groups.map(([name,items],index)=>subdimensionSection(name,items,index,d.dimension_id)).join(''):'<div class="empty"><strong>Nenhum critério encontrado</strong><span>Ajuste a busca ou os filtros selecionados.</span></div>';
 document.querySelectorAll('.audit-subdimension-nav a').forEach(link=>link.onclick=event=>{event.preventDefault();document.getElementById(link.getAttribute('href').slice(1))?.scrollIntoView({behavior:'smooth',block:'start'});});
}

async function init(){
 report=load();if(report?.method!==modelVersion)report=null;
 if(!report){try{const response=await fetch('/api/maturity/cache/latest');if(response.ok){const cached=await response.json();if(cached.method===modelVersion){report=cached;localStorage.setItem(storeKey,JSON.stringify(report));}}}catch{}}
 try{const response=await fetch('/api/maturity/dimensions');if(response.ok)catalog=await response.json();}catch{}
 if(!report?.dimensions?.length){document.getElementById('audit-log').innerHTML='<div class="empty">Nenhum processamento compatível salvo. Execute uma avaliação de maturidade.</div>';document.getElementById('audit-title').textContent='Sem processamento';document.getElementById('contract-health').textContent='Sem relatório para validar';return;}
 if(!report.dimensions.some(d=>d.dimension_id===activeId))activeId=report.dimensions[0].dimension_id;renderSummary();validateContract();renderTabs();renderDimension();document.getElementById('generate-report').disabled=false;
}
async function generateReport(){const button=document.getElementById('generate-report'),original=button.innerHTML;button.disabled=true;button.innerHTML='<span>◌</span> Gerando PDF…';try{const response=await fetch('/api/maturity/report-pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({report:report})});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.detail||'Falha ao gerar o relatório');}const blob=await response.blob(),disposition=response.headers.get('content-disposition')||'',match=disposition.match(/filename="?([^";]+)"?/i),filename=(match&&match[1])||('relatorio-maturidade-'+((report.context&&report.context.project_name)||'microservico')+'.pdf'),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);button.innerHTML='<span>✓</span> Relatório gerado';setTimeout(()=>button.innerHTML=original,1800);}catch(error){button.innerHTML='<span>!</span> '+escapeHtml(error.message);setTimeout(()=>button.innerHTML=original,2500);}finally{button.disabled=false;}}
document.getElementById('generate-report').onclick=generateReport;
document.getElementById('status-filter').onchange=event=>{statusFilter=event.target.value;renderDimension();};document.getElementById('result-filter').onchange=event=>{resultFilter=event.target.value;renderDimension();};document.getElementById('audit-search').oninput=event=>{queryFilter=event.target.value.trim().toLowerCase();renderDimension();};init();
