const dimensions=[
  {id:'CODE_QUALITY',name:'Qualidade de Código'},
  {id:'SOFTWARE_DESIGN',name:'Design de Software'},
  {id:'RESILIENCE',name:'Resiliência'},
  {id:'SECURITY',name:'Segurança'},
  {id:'OBSERVABILITY',name:'Observabilidade'},
  {id:'OPERABILITY',name:'Operabilidade'}
];
const list=document.getElementById('dimension-list'),statusText=document.getElementById('current-status'),scorePanel=document.getElementById('score-panel'),assessmentTitle=document.getElementById('assessment-title');
let cancelled=false,dimensionResults=[],consolidated=null;
const resultBadge=document.querySelector('.result-heading .simulation-badge');if(resultBadge)resultBadge.textContent='6 dimensões · 69 critérios · v1.0';
function context(){try{return JSON.parse(sessionStorage.getItem('expert-code-flow:maturity-context')||localStorage.getItem('expert-code-flow:maturity-context'))||{};}catch{return {};}}
function renderContext(){const data=context();document.getElementById('service-name').textContent=data.project_name||'Microsserviço analisado';document.getElementById('architecture-name').textContent=data.architecture||'—';document.getElementById('endpoint-name').textContent=data.endpoint||'—';}
function renderRows(){list.innerHTML=dimensions.map((d,i)=>`<article class="dimension pending" id="dimension-${i}"><span class="dimension-state" aria-hidden="true">${i+1}</span><div><b>${i+1}. ${d.name}</b><div class="progress-track"><i></i></div></div><strong class="dimension-percent">0%</strong></article>`).join('');}
function wait(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
function coverageLabel(value){return value===null?'N/A':`${value}%`;}
async function requestJson(url,options){const response=await fetch(url,options);if(!response.ok){let detail=`HTTP ${response.status}`;try{detail=(await response.json()).detail||detail;}catch{}throw new Error(detail);}return response.json();}
async function animateProgress(row,from,to,delay=12){const bar=row.querySelector('.progress-track i'),percent=row.querySelector('.dimension-percent'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;for(let value=from;value<=to;value+=2){if(cancelled)return false;bar.style.width=`${value}%`;percent.textContent=`${value}%`;await wait(reduced?2:delay);}return true;}
async function processDimension(index,projectPath){const d=dimensions[index],row=document.getElementById(`dimension-${index}`),state=row.querySelector('.dimension-state');row.className='dimension active';state.textContent='▶';statusText.textContent=`Avaliando ${d.name} no código-fonte…`;const evaluation=requestJson('/api/maturity/evaluate-dimension',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_path:projectPath,dimension_id:d.id})});if(!await animateProgress(row,0,84,15))return null;const result=await evaluation;if(!await animateProgress(row,86,100,8))return null;row.className='dimension completed';state.textContent='✓';row.title=`Score ${result.score===null?'não calculado':result.score+'/100'} · cobertura ${coverageLabel(result.coverage_percent)}`;return result;}
function point(cx,cy,r,index,total=dimensions.length){const angle=-Math.PI/2+(Math.PI*2*index/total);return [cx+Math.cos(angle)*r,cy+Math.sin(angle)*r];}
function pointsAt(cx,cy,r){return dimensions.map((_,i)=>point(cx,cy,r,i).join(',')).join(' ');}
function renderRadar(scores){const svg=document.getElementById('maturity-radar'),cx=340,cy=285,radius=205;let c='<defs><linearGradient id="radar-fill"><stop stop-color="#54e6cf" stop-opacity=".4"/><stop offset="1" stop-color="#b5f44a" stop-opacity=".18"/></linearGradient></defs>';for(let level=1;level<=5;level++)c+=`<polygon class="radar-grid" points="${pointsAt(cx,cy,radius*level/5)}"/>`;dimensions.forEach((d,i)=>{const [x,y]=point(cx,cy,radius,i),[lx,ly]=point(cx,cy,radius+48,i),anchor=lx<cx-10?'end':lx>cx+10?'start':'middle',label=d.name;c+=`<line class="radar-axis" x1="${cx}" y1="${cy}" x2="${x}" y2="${y}"/><text class="radar-label" x="${lx}" y="${ly}" text-anchor="${anchor}">${label}</text>`;});const applicablePoints=scores.flatMap((score,index)=>score===null?[]:[point(cx,cy,radius*score/100,index).join(',')]);c+=`<polygon class="radar-reference" points="${dimensions.map((_,i)=>point(cx,cy,radius*.7,i).join(',')).join(' ')}"/>`;if(applicablePoints.length>2)c+=`<polygon class="radar-value" points="${applicablePoints.join(' ')}"/>`;scores.forEach((score,index)=>{if(score===null){const [labelX,labelY]=point(cx,cy,radius+72,index);c+=`<text class="radar-score na-label" x="${labelX}" y="${labelY+5}">N/A</text>`;return;}const tone=resultTone(score),[x,y]=point(cx,cy,radius*score/100,index),labelRadius=score===0?22:Math.max(radius*score/100+18,34),[labelX,labelY]=point(cx,cy,labelRadius,index);c+=`<circle class="radar-dot ${tone}" cx="${x}" cy="${y}" r="${score===0?5:6}"/><text class="radar-score ${tone}" x="${labelX}" y="${labelY+5}">${score}</text>`;});svg.innerHTML=c;}
function getMaturityLevel(score){
 const normalized=Math.max(0,Math.min(100,Number(score)||0)),levels=[
  {label:'CRÍTICO',start:0,end:29,color:'#ff5964',description:'Maturidade insuficiente'},
  {label:'BAIXO',start:30,end:49,color:'#f39a32',description:'Maturidade inicial'},
  {label:'MÉDIO',start:50,end:69,color:'#d8ef3f',description:'Maturidade em evolução'},
  {label:'BOM',start:70,end:89,color:'#79d83d',description:'Maturidade estabelecida'},
  {label:'EXCELENTE',start:90,end:100,color:'#54e6cf',description:'Maturidade avançada'}
 ],index=levels.findIndex(level=>normalized>=level.start&&normalized<=level.end),level=levels[index],nextLevel=levels[index+1]||null;
 return {...level,score:normalized,levels,nextLevel,pointsRemaining:nextLevel?Math.max(0,nextLevel.start-normalized):0};
}
function classification(score){const level=getMaturityLevel(score);return [level.label[0]+level.label.slice(1).toLowerCase(),level.description.replace('Maturidade ','')];}
function renderGauge(score){const cx=130,cy=135,r=92,start=Math.PI,end=Math.PI*2,arc=(from,to)=>{const a=point(cx,cy,r,(from+Math.PI/2)/(Math.PI*2),1),b=point(cx,cy,r,(to+Math.PI/2)/(Math.PI*2),1);return `M${a[0]} ${a[1]} A${r} ${r} 0 0 1 ${b[0]} ${b[1]}`;},progress=start+(end-start)*score/100;document.getElementById('score-gauge').innerHTML=`<path class="gauge-track" d="${arc(start,end-.001)}"/><path class="gauge-value" d="${arc(start,progress)}"/><text class="gauge-number" x="130" y="112">${score}</text><text class="gauge-total" x="130" y="135">/ 100</text>`;}
function renderMaturityScale(score){const data=getMaturityLevel(score),scale=document.getElementById('maturity-level-scale'),markerPosition=Math.max(1,Math.min(99,data.score));scale.innerHTML=`<div class="maturity-level-labels">${data.levels.map(level=>`<span style="--level-color:${level.color}"><b>${level.label}</b><small>${level.start}–${level.end}</small></span>`).join('')}</div><div class="maturity-scale-track" aria-label="Score ${data.score} de 100"><i class="scale-critical"></i><i class="scale-low"></i><i class="scale-medium"></i><i class="scale-good"></i><i class="scale-excellent"></i><span class="maturity-scale-marker" style="left:${markerPosition}%;--marker-color:${data.color}"><b>${data.score}</b><small>Você está aqui</small></span></div><div class="maturity-next-level">${data.nextLevel?`<span>↗ Próximo nível: <b>${data.nextLevel.label} (${data.nextLevel.start})</b></span><span>Faltam <strong>${data.pointsRemaining} pontos</strong></span>`:`<span>✓ Nível máximo alcançado</span><span><strong>${data.label}</strong></span>`}</div>`;}
function resultTone(score){if(score===null)return'na';if(score>=90)return'excellent';if(score>=70)return'good';if(score>=50)return'medium';if(score>0)return'low';return'critical';}
function confidencePt(value){return({HIGH:'Alta',MEDIUM:'Média',LOW:'Baixa',NOT_AVAILABLE:'Não disponível'})[value]||value||'—';}
function deriveHighlights(results){
 const ranked=results.filter(result=>Number.isFinite(result.score)).slice().sort((a,b)=>b.score-a.score),strongest=ranked[0],weakest=ranked.at(-1),middle=ranked.slice(1,-1),attention=middle.length?middle.slice().sort((a,b)=>Math.abs(70-a.score)-Math.abs(70-b.score))[0]:ranked.find(result=>result!==strongest&&result!==weakest);
 const total=result=>result?.summary?.total||0,adherent=result=>result?.summary?.ADHERENT||0,partial=result=>result?.summary?.PARTIALLY_ADHERENT||0,nonAdherent=result=>result?.summary?.NON_ADHERENT||0,notEvaluated=result=>result?.summary?.NOT_EVALUATED||0;
 return [
  strongest&&{type:'strength',label:'Ponto forte',icon:'◎',result:strongest,copy:`${adherent(strongest)} de ${total(strongest)} critérios aderentes nesta dimensão.`},
  attention&&{type:'attention',label:'Atenção',icon:'△',result:attention,copy:`${partial(attention)} critérios parciais e ${nonAdherent(attention)} não aderentes requerem acompanhamento.`},
  weakest&&weakest!==strongest&&{type:'priority',label:'Prioridade',icon:'◇',result:weakest,copy:`${nonAdherent(weakest)} critérios não aderentes e ${notEvaluated(weakest)} ainda não avaliados.`}
 ].filter(Boolean);
}
function deriveRecommendations(results,limit=3){
 const dimensionScore=new Map(results.map(result=>[result.dimension_id,result.score])),priority={NON_ADHERENT:0,PARTIALLY_ADHERENT:1,NOT_EVALUATED:2};
 const findings=results.flatMap(result=>(result.criteria||[]).map(criterion=>({...criterion,dimensionId:result.dimension_id,dimensionScore:dimensionScore.get(result.dimension_id)}))).filter(criterion=>criterion.result==='NON_ADHERENT'||criterion.result==='PARTIALLY_ADHERENT'||criterion.processing_status==='NOT_EVALUATED').sort((a,b)=>(priority[a.result]??priority[a.processing_status]??3)-(priority[b.result]??priority[b.processing_status]??3)||(a.dimensionScore??101)-(b.dimensionScore??101));
 const seen=new Set(),recommendations=[];for(const finding of findings){const key=`${finding.dimensionId}:${finding.subdimension}`;if(seen.has(key))continue;seen.add(key);recommendations.push(finding);if(recommendations.length===limit)break;}return recommendations;
}
function renderResults(){
 const scores=dimensionResults.map(result=>result.score),score=consolidated.score||0,[label,level]=classification(score),foundation=consolidated.foundation||{},total=dimensionResults.reduce((sum,result)=>sum+(result.summary.total||0),0),adherent=dimensionResults.reduce((sum,result)=>sum+(result.summary.ADHERENT||0),0),notApplicable=dimensionResults.reduce((sum,result)=>sum+(result.summary.NOT_APPLICABLE||0),0);
 renderRadar(scores);renderGauge(score);renderMaturityScale(score);document.getElementById('gauge-classification').textContent=label;document.getElementById('gauge-level').textContent=`Nível ${level}`;document.getElementById('general-context').textContent=`Cobertura ${consolidated.coverage_percent??'—'}% · Confiança ${confidencePt(consolidated.confidence)}`;document.getElementById('total-criteria').textContent=total;document.getElementById('adherent-criteria').textContent=adherent;document.getElementById('not-applicable-criteria').textContent=notApplicable;
 const highlights=deriveHighlights(dimensionResults);
 document.getElementById('evaluation-highlights').innerHTML=highlights.map(item=>`<article class="highlight ${item.type}"><span>${item.icon}</span><div><small>${item.label}</small><b>${escapeResult(item.result.dimension)}</b><p>${escapeResult(item.copy)}</p></div><strong>${item.result.score}<em>/100</em></strong></article>`).join('')||'<p>Não há dimensões aplicáveis suficientes para gerar destaques.</p>';
 const recommendations=deriveRecommendations(dimensionResults);
 document.getElementById('recommendations').innerHTML=recommendations.map((item,index)=>`<article><span>${String(index+1).padStart(2,'0')}</span><div><b>Evoluir ${escapeResult(item.subdimension)}</b><p>${escapeResult(item.reason||item.finding||'Critério requer atenção.')}</p></div><a aria-label="Ver ${escapeResult(item.subdimension)} na auditoria" href="/auditoria-maturidade?dimension=${encodeURIComponent(item.dimensionId)}">›</a></article>`).join('')||'<p>Nenhuma recomendação prioritária foi identificada nesta avaliação.</p>';
 document.getElementById('dimension-score-cards').innerHTML=dimensionResults.map((result,index)=>{const tone=resultTone(result.score),dimension=dimensions[index],[dimensionLabel]=classification(result.score||0);return `<article class="dimension-score-card ${tone}" id="dimension-card-${result.dimension_id}"><header><span>${String(index+1).padStart(2,'0')}</span><b>${dimension.name}</b></header><strong>${result.score===null?'N/A':result.score+'<small>/100</small>'}</strong><em>${result.score===null?'Não aplicável':dimensionLabel}</em><div class="dimension-progress"><i style="width:${result.score||0}%"></i></div><p>${result.summary.ADHERENT||0} aderentes · ${result.summary.PARTIALLY_ADHERENT||0} parciais · ${result.summary.NON_ADHERENT||0} não aderentes</p><a href="/auditoria-maturidade?dimension=${result.dimension_id}">Detalhar →</a></article>`;}).join('');
}
function failAssessment(error,index){const row=document.getElementById(`dimension-${index}`);if(row){row.className='dimension error';row.querySelector('.dimension-state').textContent='!';}assessmentTitle.textContent='Avaliação interrompida';statusText.textContent=`Não foi possível avaliar: ${error.message}`;}
async function startAssessment(){cancelled=true;await wait(20);cancelled=false;dimensionResults=[];consolidated=null;scorePanel.hidden=true;assessmentTitle.textContent='Avaliação em andamento';renderRows();const projectPath=context().project_path;if(!projectPath){assessmentTitle.textContent='Selecione um microsserviço';statusText.textContent='Volte ao Code Flow, analise um endpoint e então inicie a avaliação de maturidade.';return;}for(let i=0;i<dimensions.length;i++){try{const result=await processDimension(i,projectPath);if(!result)return;dimensionResults.push(result);}catch(error){failAssessment(error,i);return;}}try{consolidated=await requestJson('/api/maturity/consolidate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({results:dimensionResults})});}catch(error){failAssessment(error,dimensions.length-1);return;}consolidated.generated_at=new Date().toISOString();consolidated.context=context();localStorage.setItem('expert-code-flow:maturity-results',JSON.stringify(consolidated));try{await requestJson('/api/maturity/cache',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({report:consolidated})});}catch(error){console.warn('Cache local do servidor indisponível:',error);}statusText.textContent=`${consolidated.evaluated_criteria} critérios avaliados; ${consolidated.not_evaluated_criteria} ainda aguardam heurística.`;assessmentTitle.textContent='Avaliação concluída';await wait(250);renderResults();scorePanel.hidden=false;scorePanel.scrollIntoView({behavior:'smooth',block:'start'});}
function normalizeProjectPath(value=''){return String(value).replaceAll('\\','/').replace(/\/$/,'').toLowerCase();}
function restoreLastAssessment(saved){try{saved=saved||JSON.parse(localStorage.getItem('expert-code-flow:maturity-results'));if(!saved?.dimensions?.length)return false;const activeContext=context(),savedContext=saved.context||{},activePath=normalizeProjectPath(activeContext.project_path),savedPath=normalizeProjectPath(savedContext.project_path);if(activePath&&(!savedPath||activePath!==savedPath))return false;const effectiveContext=activePath?{...savedContext,...activeContext}:savedContext;saved.context=effectiveContext;localStorage.setItem('expert-code-flow:maturity-results',JSON.stringify(saved));consolidated=saved;dimensionResults=saved.dimensions;document.getElementById('service-name').textContent=effectiveContext.project_name||'Microsserviço analisado';document.getElementById('architecture-name').textContent=effectiveContext.architecture||'—';document.getElementById('endpoint-name').textContent=effectiveContext.endpoint||'—';renderRows();dimensionResults.forEach((result,index)=>{const row=document.getElementById(`dimension-${index}`);row.className='dimension completed';row.querySelector('.dimension-state').textContent='✓';row.querySelector('.progress-track i').style.width='100%';row.querySelector('.dimension-percent').textContent='100%';row.title=`Score ${result.score===null?'não calculado':result.score+'/100'} · cobertura ${result.coverage_percent}%`;});assessmentTitle.textContent='Última avaliação concluída';statusText.textContent=`Último processamento: ${new Date(saved.generated_at).toLocaleString('pt-BR')} · ${saved.evaluated_criteria} critérios avaliados.`;renderResults();scorePanel.hidden=false;return true;}catch{return false;}}
async function initialize(){renderContext();renderRows();if(restoreLastAssessment())return;try{const path=context().project_path,query=path?`?project_path=${encodeURIComponent(path)}`:'';const saved=await requestJson(`/api/maturity/cache/latest${query}`);if(saved.method==='SIX_DIMENSIONS_OBJECTIVE_MODEL_1.0'&&restoreLastAssessment(saved))return;}catch{}setTimeout(startAssessment,500);}
try{const previous=JSON.parse(localStorage.getItem('expert-code-flow:maturity-results'));if(previous?.method!=='SIX_DIMENSIONS_OBJECTIVE_MODEL_1.0')localStorage.removeItem('expert-code-flow:maturity-results');}catch{localStorage.removeItem('expert-code-flow:maturity-results');}
function escapeResult(value=''){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
async function exportMaturityReport(){const button=document.getElementById('result-export'),original=button.textContent;button.disabled=true;button.textContent='Gerando relatório…';try{const response=await fetch('/api/maturity/report-pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({report:consolidated})});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).detail||'Falha ao gerar relatório');const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`relatorio-maturidade-${consolidated.context?.project_name||'microservico'}.pdf`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);button.textContent='Relatório gerado ✓';}catch(error){button.textContent=error.message;}finally{setTimeout(()=>{button.textContent=original;button.disabled=false;},1800);}}
async function openResultXray(){const dialog=document.getElementById('result-xray-dialog'),content=document.getElementById('result-xray-content'),project=context().project_path;dialog.showModal();content.innerHTML='<p class="xray-state">Mapeando o microsserviço…</p>';try{const data=await requestJson('/api/microservice-xray?project='+encodeURIComponent(project)),code=data.code||{},architecture=data.architecture||{},integrations=data.integrations||{},versions=data.versions||{};const group=(title,items)=>`<section><h4>${title}</h4>${items.map(([label,value])=>`<div><span>${escapeResult(label)}</span><b>${escapeResult(value??0)}</b></div>`).join('')}</section>`;content.innerHTML='<div class="result-xray-grid">'+group('Dimensão do código',[['Arquivos Java',code.java_files],['Classes',code.classes],['Interfaces',code.interfaces],['Métodos',code.methods],['Linhas de código',code.lines_of_code],['Dependências',code.dependencies]])+group('Spring e arquitetura',[['Controllers',architecture.rest_controllers],['Endpoints',architecture.rest_endpoints],['Services',architecture.services],['Ports IN',architecture.ports_in],['Ports OUT',architecture.ports_out],['Adapters OUT',architecture.adapters_out],['Repositories',architecture.repositories],['Entidades JPA',architecture.jpa_entities]])+group('Integrações',[['Chamadas externas',integrations.external_calls],['Bancos',integrations.databases],['Produtores de eventos',integrations.event_producers],['Consumidores de eventos',integrations.event_consumers]])+group('Versões',Object.entries(versions))+'</div>';}catch(error){content.innerHTML=`<p class="xray-state">${escapeResult(error.message)}</p>`;}}
document.getElementById('result-export').onclick=exportMaturityReport;document.getElementById('result-xray').onclick=openResultXray;document.getElementById('result-xray-close').onclick=()=>document.getElementById('result-xray-dialog').close();document.getElementById('result-tabs').addEventListener('click',event=>{const link=event.target.closest('a');if(!link)return;event.preventDefault();document.querySelectorAll('.result-tabs a').forEach(item=>item.classList.toggle('active',item===link));document.querySelector(link.getAttribute('href'))?.scrollIntoView({behavior:'smooth',block:'start'});});
document.getElementById('restart-assessment').onclick=startAssessment;initialize();
document.getElementById('result-xray').addEventListener('click',()=>{if(consolidated?.context)sessionStorage.setItem('expert-code-flow:maturity-context',JSON.stringify(consolidated.context));},{capture:true});
window.addEventListener('storage',event=>{if(event.key==='expert-code-flow:maturity-context'&&event.newValue&&event.newValue!==event.oldValue)location.reload();});
