const escapeHtml=value=>String(value??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]));
let catalog={rules:[],return_rules:[],responsibilities:[],intent_mappings:[],operation_mappings:[],summary:{}};

document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('[data-panel]').forEach(panel=>panel.hidden=panel.dataset.panel!==button.dataset.tab);}));

function renderResponsibilities(){document.getElementById('responsibilities').innerHTML=catalog.responsibilities.map(item=>`<article><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.role)}</small><p>${escapeHtml(item.responsibility)}</p><code>${escapeHtml(item.source_file)}</code></article>`).join('');}
function renderMappings(){document.getElementById('intent-mappings').innerHTML=catalog.intent_mappings.map(item=>`<article><code>${escapeHtml(item.http_method)} ${escapeHtml(item.path_pattern)}</code><i>→</i><b>${escapeHtml(item.intent)}</b><small>${escapeHtml(item.evidence)}</small></article>`).join('');document.getElementById('operation-mappings').innerHTML=catalog.operation_mappings.map(item=>`<article><code>${escapeHtml(item.patterns.join(', '))}</code><i>→</i><b>${escapeHtml(item.operation_kind)}</b></article>`).join('');}
function allRules(){return [...catalog.rules,...catalog.return_rules];}
function renderRules(){const search=document.getElementById('rule-search').value.toLowerCase(),intent=document.getElementById('intent-filter').value,operation=document.getElementById('operation-filter').value,type=document.getElementById('type-filter').value;const rules=allRules().filter(rule=>(!search||JSON.stringify(rule).toLowerCase().includes(search))&&(!intent||rule.endpoint_intent===intent)&&(!operation||rule.operation_kind===operation)&&(!type||rule.type===type));document.getElementById('rule-list').innerHTML=rules.length?rules.map(rule=>`<details class="rule-card"><summary><span class="rule-type ${escapeHtml(rule.type.toLowerCase())}">${escapeHtml(rule.type)}</span><b>${escapeHtml(rule.source_role)} → ${escapeHtml(rule.target_role)}</b><code>${escapeHtml(rule.endpoint_intent||'*')} + ${escapeHtml(rule.operation_kind)}</code></summary><div><p>${escapeHtml(rule.template)}</p><dl><dt>ID</dt><dd>${escapeHtml(rule.id)}</dd><dt>Origem</dt><dd>${escapeHtml(rule.source_role)}</dd><dt>Destino</dt><dd>${escapeHtml(rule.target_role)}</dd><dt>Intent</dt><dd>${escapeHtml(rule.endpoint_intent||'*')}</dd><dt>Operação</dt><dd>${escapeHtml(rule.operation_kind)}</dd><dt>Arquivo</dt><dd>${escapeHtml(rule.source_file)}</dd></dl><button class="copy-rule" data-rule-id="${escapeHtml(rule.id)}">Copiar regra</button></div></details>`).join(''):'<p class="empty">Nenhuma regra encontrada para os filtros selecionados.</p>';document.querySelectorAll('.copy-rule').forEach(button=>button.addEventListener('click',()=>copyRule(button.dataset.ruleId)));}
async function copyRule(id){const rule=allRules().find(item=>item.id===id);if(!rule)return;await navigator.clipboard.writeText(JSON.stringify(rule,null,2));}
function configureFilters(){const rules=allRules(),intents=[...new Set(rules.map(r=>r.endpoint_intent).filter(value=>value&&value!=='*'))].sort(),operations=[...new Set(rules.map(r=>r.operation_kind))].sort();document.getElementById('intent-filter').innerHTML+=[...intents].map(value=>`<option>${escapeHtml(value)}</option>`).join('');document.getElementById('operation-filter').innerHTML+=operations.map(value=>`<option>${escapeHtml(value)}</option>`).join('');['rule-search','intent-filter','operation-filter','type-filter'].forEach(id=>document.getElementById(id).addEventListener(id==='rule-search'?'input':'change',renderRules));document.getElementById('catalog-counters').innerHTML=`<span>${catalog.summary.exact_rules} exatas</span><span>${catalog.summary.relation_rules} por relação</span><span>${catalog.summary.fallback_rules} fallbacks</span><span>${catalog.summary.return_rules} retornos</span>`;}
function renderAudit(){const stored=sessionStorage.getItem('expert-code-flow:last-semantic-analysis'),target=document.getElementById('semantic-audit');if(!stored)return;try{const data=JSON.parse(stored),flow=data.semantic_flow,context=flow.endpoint_context,participants=Object.fromEntries(flow.participants.map(p=>[p.id,p])),exact=flow.interactions.filter(i=>i.rule_level==='EXACT').length,fallbacks=flow.interactions.filter(i=>i.rule_level.includes('FALLBACK')).length;target.className='';target.innerHTML=`<div class="audit-summary"><span><b>Endpoint:</b> ${escapeHtml(context.http_method)} ${escapeHtml(context.path)}</span><span><b>Intent:</b> ${escapeHtml(context.intent)}</span><span><b>Entidade:</b> ${escapeHtml(context.entity)}</span><span><b>Confiança:</b> ${escapeHtml(context.confidence)}%</span><span><b>Regras exatas:</b> ${exact}</span><span><b>Fallbacks:</b> ${fallbacks}</span></div><table class="audit-table"><thead><tr><th>Origem</th><th>Destino</th><th>Operação</th><th>Regra</th><th>Mensagem</th></tr></thead><tbody>${flow.interactions.map(item=>`<tr><td>${escapeHtml(participants[item.source]?.display_name)}</td><td>${escapeHtml(participants[item.target]?.display_name)}</td><td>${escapeHtml(item.operation_kind)}</td><td>${escapeHtml(item.rule_level)}</td><td>${escapeHtml(item.functional_description)}</td></tr>`).join('')}</tbody></table>`;}catch(error){target.textContent='Não foi possível carregar a última análise.';}}
fetch('/api/semantic/catalog').then(response=>{if(!response.ok)throw new Error('Falha ao carregar catálogo');return response.json();}).then(data=>{catalog=data;renderResponsibilities();renderMappings();configureFilters();renderRules();}).catch(error=>{document.getElementById('rule-list').textContent=error.message;});renderAudit();
